import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('hi'),
    Locale('ta'),
    Locale('te'),
    Locale('ml'),
    Locale('kn'),
    Locale('pa'),
    Locale('bn'),
    Locale('or'),
    Locale('as'),
    Locale('gu'),
  ];

  static const languageNames = {
    'en': 'English',
    'hi': 'हिन्दी',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'ml': 'മലയാളം',
    'kn': 'ಕನ್ನಡ',
    'pa': 'ਪੰਜਾਬੀ',
    'bn': 'বাংলা',
    'or': 'ଓଡ଼ିଆ',
    'as': 'অসমীয়া',
    'gu': 'ગુજરાતી',
  };

  static const _values = <String, Map<String, String>>{
    'en': {
      'tagline': 'Score every ball. Anywhere.',
      'startMatch': 'Start Match',
      'matchHistory': 'Match History',
      'watchLive': 'Watch Live Match',
      'matchCode': 'Enter match code',
      'find': 'Find',
      'cloudBackup': 'Cloud backup',
      'online': 'Online',
      'offline': 'Offline - saved locally',
      'syncing': 'Syncing...',
      'continueMatch': 'Continue Match',
      'language': 'Language',
      'developedBy': 'Developed by K.K. & Co.',
      'poweredBy': 'Powered by KK Bharat',
      'liveScoreboard': 'Live Scoreboard',
      'invalidCode': 'Match code not found.',
      'batting': 'Batting',
      'bowling': 'Bowling',
      'overs': 'Overs',
      'striker': 'Striker',
      'nonStriker': 'Non-striker',
      'bowler': 'Bowler',
      'lastOver': 'Last over',
    },
    'hi': {
      'tagline': 'हर गेंद का स्कोर, कहीं भी।',
      'startMatch': 'मैच शुरू करें',
      'matchHistory': 'मैच इतिहास',
      'watchLive': 'लाइव मैच देखें',
      'matchCode': 'मैच कोड दर्ज करें',
      'find': 'खोजें',
      'cloudBackup': 'क्लाउड बैकअप',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन - फोन में सुरक्षित',
      'syncing': 'सिंक हो रहा है...',
      'continueMatch': 'मैच जारी रखें',
      'language': 'भाषा',
      'developedBy': 'डेवलपर K.K. एंड कंपनी',
      'poweredBy': 'KK Bharat द्वारा संचालित',
      'liveScoreboard': 'लाइव स्कोरबोर्ड',
      'invalidCode': 'मैच कोड नहीं मिला।',
      'batting': 'बल्लेबाजी',
      'bowling': 'गेंदबाजी',
      'overs': 'ओवर',
      'striker': 'स्ट्राइकर',
      'nonStriker': 'नॉन-स्ट्राइकर',
      'bowler': 'गेंदबाज',
      'lastOver': 'पिछला ओवर',
    },
    'ta': {
      'tagline': 'ஒவ்வொரு பந்தையும் எங்கும் பதிவு செய்யுங்கள்.',
      'startMatch': 'போட்டியை தொடங்கு',
      'matchHistory': 'போட்டி வரலாறு',
      'watchLive': 'நேரலை போட்டி',
      'matchCode': 'போட்டி குறியீடு',
      'find': 'தேடு',
      'cloudBackup': 'கிளவுட் காப்பு',
      'online': 'இணையத்தில்',
      'offline': 'இணையமில்லை - உள்ளூரில் சேமிப்பு',
      'syncing': 'ஒத்திசைக்கிறது...',
      'continueMatch': 'போட்டியை தொடர்க',
      'language': 'மொழி',
      'developedBy': 'K.K. & Co. உருவாக்கியது',
      'poweredBy': 'KK Bharat ஆதரவு',
      'liveScoreboard': 'நேரலை ஸ்கோர்போர்டு',
      'invalidCode': 'போட்டி குறியீடு கிடைக்கவில்லை.',
    },
    'te': {
      'tagline': 'ప్రతి బంతిని ఎక్కడైనా స్కోర్ చేయండి.',
      'startMatch': 'మ్యాచ్ ప్రారంభించండి',
      'matchHistory': 'మ్యాచ్ చరిత్ర',
      'watchLive': 'లైవ్ మ్యాచ్ చూడండి',
      'matchCode': 'మ్యాచ్ కోడ్',
      'find': 'వెతకండి',
      'cloudBackup': 'క్లౌడ్ బ్యాకప్',
      'online': 'ఆన్‌లైన్',
      'offline': 'ఆఫ్‌లైన్ - ఫోన్‌లో భద్రం',
      'syncing': 'సింక్ అవుతోంది...',
      'continueMatch': 'మ్యాచ్ కొనసాగించండి',
      'language': 'భాష',
      'developedBy': 'K.K. & Co. అభివృద్ధి',
      'poweredBy': 'KK Bharat ద్వారా',
      'liveScoreboard': 'లైవ్ స్కోర్‌బోర్డ్',
      'invalidCode': 'మ్యాచ్ కోడ్ కనుగొనబడలేదు.',
    },
    'ml': {
      'tagline': 'ഓരോ പന്തും എവിടെയും സ്കോർ ചെയ്യുക.',
      'startMatch': 'മത്സരം ആരംഭിക്കുക',
      'matchHistory': 'മത്സര ചരിത്രം',
      'watchLive': 'തത്സമയ മത്സരം',
      'matchCode': 'മാച്ച് കോഡ്',
      'find': 'കണ്ടെത്തുക',
      'cloudBackup': 'ക്ലൗഡ് ബാക്കപ്പ്',
      'online': 'ഓൺലൈൻ',
      'offline': 'ഓഫ്‌ലൈൻ - ഫോണിൽ സൂക്ഷിച്ചു',
      'syncing': 'സിങ്ക് ചെയ്യുന്നു...',
      'continueMatch': 'മത്സരം തുടരുക',
      'language': 'ഭാഷ',
      'developedBy': 'K.K. & Co. വികസിപ്പിച്ചത്',
      'poweredBy': 'KK Bharat നൽകുന്നു',
      'liveScoreboard': 'തത്സമയ സ്കോർബോർഡ്',
      'invalidCode': 'മാച്ച് കോഡ് കണ്ടെത്തിയില്ല.',
    },
    'kn': {
      'tagline': 'ಪ್ರತಿ ಚೆಂಡಿನ ಸ್ಕೋರ್ ಎಲ್ಲೆಡೆ.',
      'startMatch': 'ಪಂದ್ಯ ಪ್ರಾರಂಭಿಸಿ',
      'matchHistory': 'ಪಂದ್ಯ ಇತಿಹಾಸ',
      'watchLive': 'ಲೈವ್ ಪಂದ್ಯ ನೋಡಿ',
      'matchCode': 'ಪಂದ್ಯ ಕೋಡ್',
      'find': 'ಹುಡುಕಿ',
      'cloudBackup': 'ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್',
      'online': 'ಆನ್‌ಲೈನ್',
      'offline': 'ಆಫ್‌ಲೈನ್ - ಫೋನ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ',
      'syncing': 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
      'continueMatch': 'ಪಂದ್ಯ ಮುಂದುವರಿಸಿ',
      'language': 'ಭಾಷೆ',
      'developedBy': 'K.K. & Co. ಅಭಿವೃದ್ಧಿ',
      'poweredBy': 'KK Bharat ಮೂಲಕ',
      'liveScoreboard': 'ಲೈವ್ ಸ್ಕೋರ್‌ಬೋರ್ಡ್',
      'invalidCode': 'ಪಂದ್ಯ ಕೋಡ್ ಸಿಗಲಿಲ್ಲ.',
    },
    'pa': {
      'tagline': 'ਹਰ ਗੇਂਦ ਦਾ ਸਕੋਰ, ਕਿਤੇ ਵੀ।',
      'startMatch': 'ਮੈਚ ਸ਼ੁਰੂ ਕਰੋ',
      'matchHistory': 'ਮੈਚ ਇਤਿਹਾਸ',
      'watchLive': 'ਲਾਈਵ ਮੈਚ ਵੇਖੋ',
      'matchCode': 'ਮੈਚ ਕੋਡ',
      'find': 'ਲੱਭੋ',
      'cloudBackup': 'ਕਲਾਉਡ ਬੈਕਅੱਪ',
      'online': 'ਆਨਲਾਈਨ',
      'offline': 'ਆਫਲਾਈਨ - ਫੋਨ ਵਿੱਚ ਸੁਰੱਖਿਅਤ',
      'syncing': 'ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...',
      'continueMatch': 'ਮੈਚ ਜਾਰੀ ਰੱਖੋ',
      'language': 'ਭਾਸ਼ਾ',
      'developedBy': 'K.K. & Co. ਵੱਲੋਂ ਤਿਆਰ',
      'poweredBy': 'KK Bharat ਦੁਆਰਾ',
      'liveScoreboard': 'ਲਾਈਵ ਸਕੋਰਬੋਰਡ',
      'invalidCode': 'ਮੈਚ ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ।',
    },
    'bn': {
      'tagline': 'প্রতিটি বলের স্কোর, যেকোনো জায়গায়।',
      'startMatch': 'ম্যাচ শুরু করুন',
      'matchHistory': 'ম্যাচ ইতিহাস',
      'watchLive': 'লাইভ ম্যাচ দেখুন',
      'matchCode': 'ম্যাচ কোড',
      'find': 'খুঁজুন',
      'cloudBackup': 'ক্লাউড ব্যাকআপ',
      'online': 'অনলাইন',
      'offline': 'অফলাইন - ফোনে সংরক্ষিত',
      'syncing': 'সিঙ্ক হচ্ছে...',
      'continueMatch': 'ম্যাচ চালিয়ে যান',
      'language': 'ভাষা',
      'developedBy': 'K.K. & Co. নির্মিত',
      'poweredBy': 'KK Bharat দ্বারা',
      'liveScoreboard': 'লাইভ স্কোরবোর্ড',
      'invalidCode': 'ম্যাচ কোড পাওয়া যায়নি।',
    },
    'or': {
      'tagline': 'ପ୍ରତ୍ୟେକ ବଲ୍‌ର ସ୍କୋର, ସବୁଠାରେ।',
      'startMatch': 'ମ୍ୟାଚ୍ ଆରମ୍ଭ କରନ୍ତୁ',
      'matchHistory': 'ମ୍ୟାଚ୍ ଇତିହାସ',
      'watchLive': 'ଲାଇଭ୍ ମ୍ୟାଚ୍ ଦେଖନ୍ତୁ',
      'matchCode': 'ମ୍ୟାଚ୍ କୋଡ୍',
      'find': 'ଖୋଜନ୍ତୁ',
      'cloudBackup': 'କ୍ଲାଉଡ୍ ବ୍ୟାକଅପ୍',
      'online': 'ଅନଲାଇନ୍',
      'offline': 'ଅଫଲାଇନ୍ - ଫୋନ୍‌ରେ ସଂରକ୍ଷିତ',
      'syncing': 'ସିଙ୍କ ହେଉଛି...',
      'continueMatch': 'ମ୍ୟାଚ୍ ଜାରି ରଖନ୍ତୁ',
      'language': 'ଭାଷା',
      'developedBy': 'K.K. & Co. ଦ୍ୱାରା ବିକଶିତ',
      'poweredBy': 'KK Bharat ଦ୍ୱାରା',
      'liveScoreboard': 'ଲାଇଭ୍ ସ୍କୋରବୋର୍ଡ',
      'invalidCode': 'ମ୍ୟାଚ୍ କୋଡ୍ ମିଳିଲା ନାହିଁ।',
    },
    'as': {
      'tagline': 'প্ৰতিটো বলৰ স্ক’ৰ, যিকোনো ঠাইত।',
      'startMatch': 'মেচ আৰম্ভ কৰক',
      'matchHistory': 'মেচ ইতিহাস',
      'watchLive': 'লাইভ মেচ চাওক',
      'matchCode': 'মেচ ক’ড',
      'find': 'বিচাৰক',
      'cloudBackup': 'ক্লাউড বেকআপ',
      'online': 'অনলাইন',
      'offline': 'অফলাইন - ফোনত সংৰক্ষিত',
      'syncing': 'চিংক হৈ আছে...',
      'continueMatch': 'মেচ অব্যাহত ৰাখক',
      'language': 'ভাষা',
      'developedBy': 'K.K. & Co. দ্বাৰা নিৰ্মিত',
      'poweredBy': 'KK Bharat দ্বাৰা',
      'liveScoreboard': 'লাইভ স্ক’ৰবৰ্ড',
      'invalidCode': 'মেচ ক’ড পোৱা নগ’ল।',
    },
    'gu': {
      'tagline': 'દરેક બોલનો સ્કોર, ગમે ત્યાં.',
      'startMatch': 'મેચ શરૂ કરો',
      'matchHistory': 'મેચ ઇતિહાસ',
      'watchLive': 'લાઇવ મેચ જુઓ',
      'matchCode': 'મેચ કોડ દાખલ કરો',
      'find': 'શોધો',
      'cloudBackup': 'ક્લાઉડ બેકઅપ',
      'online': 'ઓનલાઇન',
      'offline': 'ઓફલાઇન - ફોનમાં સાચવેલ',
      'syncing': 'સિંક થઈ રહ્યું છે...',
      'continueMatch': 'મેચ ચાલુ રાખો',
      'language': 'ભાષા',
      'developedBy': 'K.K. & Co. દ્વારા વિકસિત',
      'poweredBy': 'KK Bharat દ્વારા સંચાલિત',
      'liveScoreboard': 'લાઇવ સ્કોરબોર્ડ',
      'invalidCode': 'મેચ કોડ મળ્યો નથી.',
      'batting': 'બેટિંગ',
      'bowling': 'બોલિંગ',
      'overs': 'ઓવર',
      'striker': 'સ્ટ્રાઇકર',
      'nonStriker': 'નોન-સ્ટ્રાઇકર',
      'bowler': 'બોલર',
      'lastOver': 'છેલ્લો ઓવર',
    },
  };

  static const _common = <String, Map<String, String>>{
    'en': {
      'continue': 'Continue',
      'back': 'Back',
      'cancel': 'Cancel',
      'save': 'Save',
      'confirm': 'Confirm',
      'teamASetup': 'Team A Setup',
      'teamBSetup': 'Team B Setup',
      'addTeamPlayers': 'Add team and players',
      'battingFirst': 'Batting First',
      'matchOvers': 'Match Overs',
      'customOvers': 'Custom overs',
      'openingPlayers': 'Opening Players',
      'chooseBattersBowler': 'Choose batters and bowler',
      'openingBatters': 'Opening Batters',
      'selectStrikerPartner': 'Select striker and non-striker',
      'openingBowler': 'Opening Bowler',
      'selectCurrentBowler': 'Select the current bowler',
      'addBatters': 'Add Batters',
      'editBatters': 'Edit Batters',
      'addBowler': 'Add Bowler',
      'editBowler': 'Edit Bowler',
      'addPlayers': 'Add Players',
      'editPlayers': 'Edit Players',
      'teamName': 'Team name',
      'players11': '11 Players',
      'tapMic': 'Tap mic to speak',
      'playerName': 'Player name',
      'scorecard': 'Scorecard',
      'wicket': 'Wicket',
      'extra': 'Extra',
      'undo': 'Undo',
      'changeBowler': 'Bowler',
      'end': 'End',
      'target': 'Target',
      'need': 'Need',
      'rrr': 'Required rate',
      'last6': 'Last 6 balls',
      'inningsBreak': 'Innings Break',
      'startChase': 'Set Players & Start Chase',
      'matchSummary': 'Match Summary',
      'currentPlayers': 'Current Players',
      'deleteMatch': 'Delete match?',
      'delete': 'Delete',
      'noMatches': 'No matches found',
      'overComplete': 'Over Complete',
      'selectNewBowler': 'Select the new bowler',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'selectExtra': 'Select extra',
      'howOut': 'How was the batter out?',
      'nextBatter': 'Next batter',
      'endMatch': 'End Match',
      'topPerformers': 'Top 3 Performers',
      'ballsLeft': 'Balls left',
      'selectStriker': 'Select the striker, then choose the non-striker',
      'selectNonStriker': 'Select the non-striker',
    },
    'hi': {
      'continue': 'आगे बढ़ें',
      'back': 'वापस',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'confirm': 'पुष्टि करें',
      'teamASetup': 'टीम A सेटअप',
      'teamBSetup': 'टीम B सेटअप',
      'addTeamPlayers': 'टीम और खिलाड़ी जोड़ें',
      'battingFirst': 'पहले बल्लेबाजी',
      'matchOvers': 'मैच ओवर',
      'customOvers': 'कस्टम ओवर',
      'openingPlayers': 'शुरुआती खिलाड़ी',
      'chooseBattersBowler': 'बल्लेबाज और गेंदबाज चुनें',
      'openingBatters': 'शुरुआती बल्लेबाज',
      'selectStrikerPartner': 'स्ट्राइकर और नॉन-स्ट्राइकर चुनें',
      'openingBowler': 'शुरुआती गेंदबाज',
      'selectCurrentBowler': 'वर्तमान गेंदबाज चुनें',
      'addBatters': 'बल्लेबाज जोड़ें',
      'editBatters': 'बल्लेबाज बदलें',
      'addBowler': 'गेंदबाज जोड़ें',
      'editBowler': 'गेंदबाज बदलें',
      'addPlayers': 'खिलाड़ी जोड़ें',
      'editPlayers': 'खिलाड़ी बदलें',
      'teamName': 'टीम का नाम',
      'players11': '11 खिलाड़ी',
      'tapMic': 'बोलने के लिए माइक दबाएँ',
      'playerName': 'खिलाड़ी का नाम',
      'scorecard': 'स्कोरकार्ड',
      'wicket': 'विकेट',
      'extra': 'अतिरिक्त',
      'undo': 'वापस लें',
      'changeBowler': 'गेंदबाज',
      'end': 'समाप्त',
      'target': 'लक्ष्य',
      'need': 'ज़रूरत',
      'rrr': 'आवश्यक रन रेट',
      'last6': 'पिछली 6 गेंदें',
      'inningsBreak': 'पारी का अंतराल',
      'startChase': 'खिलाड़ी चुनें और लक्ष्य शुरू करें',
      'matchSummary': 'मैच सारांश',
      'currentPlayers': 'वर्तमान खिलाड़ी',
      'deleteMatch': 'मैच हटाएँ?',
      'delete': 'हटाएँ',
      'noMatches': 'कोई मैच नहीं मिला',
      'overComplete': 'ओवर पूरा',
      'selectNewBowler': 'नया गेंदबाज चुनें',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',
      'selectExtra': 'अतिरिक्त चुनें',
      'howOut': 'बल्लेबाज कैसे आउट हुआ?',
      'nextBatter': 'अगला बल्लेबाज',
      'endMatch': 'मैच समाप्त करें',
      'topPerformers': 'शीर्ष 3 खिलाड़ी',
      'ballsLeft': 'गेंदें बाकी',
      'selectStriker': 'स्ट्राइकर चुनें, फिर नॉन-स्ट्राइकर चुनें',
      'selectNonStriker': 'नॉन-स्ट्राइकर चुनें',
    },
    'ta': {
      'continue': 'தொடர்க',
      'back': 'பின்செல்',
      'cancel': 'ரத்து',
      'save': 'சேமி',
      'confirm': 'உறுதி',
      'teamASetup': 'அணி A அமைப்பு',
      'teamBSetup': 'அணி B அமைப்பு',
      'addTeamPlayers': 'அணி மற்றும் வீரர்களை சேர்க்கவும்',
      'battingFirst': 'முதலில் பேட்டிங்',
      'matchOvers': 'போட்டி ஓவர்கள்',
      'customOvers': 'தனிப்பயன் ஓவர்கள்',
      'openingPlayers': 'தொடக்க வீரர்கள்',
      'chooseBattersBowler': 'பேட்டர்கள் மற்றும் பந்துவீச்சாளரை தேர்வு',
      'openingBatters': 'தொடக்க பேட்டர்கள்',
      'selectStrikerPartner': 'ஸ்ட்ரைக்கர் மற்றும் துணையை தேர்வு',
      'openingBowler': 'தொடக்க பந்துவீச்சாளர்',
      'selectCurrentBowler': 'தற்போதைய பந்துவீச்சாளரை தேர்வு',
      'addBatters': 'பேட்டர்களை சேர்க்க',
      'editBatters': 'பேட்டர்களை மாற்ற',
      'addBowler': 'பந்துவீச்சாளரை சேர்க்க',
      'editBowler': 'பந்துவீச்சாளரை மாற்ற',
      'addPlayers': 'வீரர்களை சேர்க்க',
      'editPlayers': 'வீரர்களை மாற்ற',
      'teamName': 'அணி பெயர்',
      'players11': '11 வீரர்கள்',
      'tapMic': 'பேச மைக்கை தட்டவும்',
      'playerName': 'வீரர் பெயர்',
      'scorecard': 'ஸ்கோர்கார்டு',
      'wicket': 'விக்கெட்',
      'extra': 'எக்ஸ்ட்ரா',
      'undo': 'மீட்டெடு',
      'changeBowler': 'பந்துவீச்சாளர்',
      'end': 'முடி',
      'target': 'இலக்கு',
      'need': 'தேவை',
      'rrr': 'தேவையான ரன் ரேட்',
      'last6': 'கடைசி 6 பந்துகள்',
      'inningsBreak': 'இன்னிங்ஸ் இடைவேளை',
      'startChase': 'வீரர்களை தேர்ந்து சேஸை தொடங்கு',
      'matchSummary': 'போட்டி சுருக்கம்',
      'currentPlayers': 'தற்போதைய வீரர்கள்',
      'deleteMatch': 'போட்டியை நீக்கவா?',
      'delete': 'நீக்கு',
      'noMatches': 'போட்டிகள் இல்லை',
      'overComplete': 'ஓவர் முடிந்தது',
      'selectNewBowler': 'புதிய பந்துவீச்சாளரை தேர்வு',
      'available': 'கிடைக்கும்',
      'unavailable': 'கிடைக்காது',
      'selectExtra': 'எக்ஸ்ட்ரா தேர்வு',
      'howOut': 'பேட்டர் எப்படி அவுட்?',
      'nextBatter': 'அடுத்த பேட்டர்',
      'endMatch': 'போட்டியை முடி',
      'topPerformers': 'சிறந்த 3 வீரர்கள்',
      'ballsLeft': 'மீதமுள்ள பந்துகள்',
      'selectStriker':
          'ஸ்ட்ரைக்கரை தேர்வு செய்து, பின்னர் நான்ஸ்ட்ரைக்கரை தேர்வு செய்யவும்',
      'selectNonStriker': 'நான்ஸ்ட்ரைக்கரை தேர்வு செய்யவும்',
    },
    'te': {
      'continue': 'కొనసాగించండి',
      'back': 'వెనుకకు',
      'cancel': 'రద్దు',
      'save': 'సేవ్',
      'confirm': 'నిర్ధారించండి',
      'teamASetup': 'టీమ్ A సెటప్',
      'teamBSetup': 'టీమ్ B సెటప్',
      'addTeamPlayers': 'టీమ్ మరియు ఆటగాళ్లను జోడించండి',
      'battingFirst': 'మొదట బ్యాటింగ్',
      'matchOvers': 'మ్యాచ్ ఓవర్లు',
      'customOvers': 'కస్టమ్ ఓవర్లు',
      'openingPlayers': 'ప్రారంభ ఆటగాళ్లు',
      'chooseBattersBowler': 'బ్యాటర్లు, బౌలర్‌ను ఎంచుకోండి',
      'openingBatters': 'ప్రారంభ బ్యాటర్లు',
      'selectStrikerPartner': 'స్ట్రైకర్, నాన్-స్ట్రైకర్ ఎంచుకోండి',
      'openingBowler': 'ప్రారంభ బౌలర్',
      'selectCurrentBowler': 'ప్రస్తుత బౌలర్‌ను ఎంచుకోండి',
      'addBatters': 'బ్యాటర్లను జోడించండి',
      'editBatters': 'బ్యాటర్లను మార్చండి',
      'addBowler': 'బౌలర్‌ను జోడించండి',
      'editBowler': 'బౌలర్‌ను మార్చండి',
      'addPlayers': 'ఆటగాళ్లను జోడించండి',
      'editPlayers': 'ఆటగాళ్లను మార్చండి',
      'teamName': 'టీమ్ పేరు',
      'players11': '11 ఆటగాళ్లు',
      'tapMic': 'మాట్లాడటానికి మైక్ నొక్కండి',
      'playerName': 'ఆటగాడి పేరు',
      'scorecard': 'స్కోర్‌కార్డ్',
      'wicket': 'వికెట్',
      'extra': 'ఎక్స్‌ట్రా',
      'undo': 'వెనక్కి తీసుకోండి',
      'changeBowler': 'బౌలర్',
      'end': 'ముగించు',
      'target': 'లక్ష్యం',
      'need': 'కావాలి',
      'rrr': 'అవసరమైన రన్ రేట్',
      'last6': 'చివరి 6 బంతులు',
      'inningsBreak': 'ఇన్నింగ్స్ విరామం',
      'startChase': 'ఆటగాళ్లను ఎంచుకుని ఛేజ్ ప్రారంభించండి',
      'matchSummary': 'మ్యాచ్ సారాంశం',
      'currentPlayers': 'ప్రస్తుత ఆటగాళ్లు',
      'deleteMatch': 'మ్యాచ్ తొలగించాలా?',
      'delete': 'తొలగించు',
      'noMatches': 'మ్యాచ్‌లు లేవు',
      'overComplete': 'ఓవర్ పూర్తైంది',
      'selectNewBowler': 'కొత్త బౌలర్‌ను ఎంచుకోండి',
      'available': 'అందుబాటులో',
      'unavailable': 'అందుబాటులో లేదు',
      'selectExtra': 'ఎక్స్‌ట్రా ఎంచుకోండి',
      'howOut': 'బ్యాటర్ ఎలా ఔట్ అయ్యాడు?',
      'nextBatter': 'తదుపరి బ్యాటర్',
      'endMatch': 'మ్యాచ్ ముగించండి',
      'topPerformers': 'టాప్ 3 ఆటగాళ్లు',
      'ballsLeft': 'మిగిలిన బంతులు',
      'selectStriker':
          'స్ట్రైకర్‌ను ఎంచుకుని, తర్వాత నాన్-స్ట్రైకర్‌ను ఎంచుకోండి',
      'selectNonStriker': 'నాన్-స్ట్రైకర్‌ను ఎంచుకోండి',
    },
    'ml': {
      'continue': 'തുടരുക',
      'back': 'പിന്നോട്ട്',
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സേവ്',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      'teamASetup': 'ടീം A ക്രമീകരണം',
      'teamBSetup': 'ടീം B ക്രമീകരണം',
      'addTeamPlayers': 'ടീമും കളിക്കാരെയും ചേർക്കുക',
      'battingFirst': 'ആദ്യം ബാറ്റിംഗ്',
      'matchOvers': 'മത്സര ഓവറുകൾ',
      'customOvers': 'ഇഷ്ടാനുസൃത ഓവറുകൾ',
      'openingPlayers': 'തുടക്ക കളിക്കാർ',
      'chooseBattersBowler': 'ബാറ്റർമാരെയും ബൗളറെയും തിരഞ്ഞെടുക്കുക',
      'openingBatters': 'തുടക്ക ബാറ്റർമാർ',
      'selectStrikerPartner': 'സ്ട്രൈക്കറും നോൺ-സ്ട്രൈക്കറും തിരഞ്ഞെടുക്കുക',
      'openingBowler': 'തുടക്ക ബൗളർ',
      'selectCurrentBowler': 'നിലവിലെ ബൗളറെ തിരഞ്ഞെടുക്കുക',
      'addBatters': 'ബാറ്റർമാരെ ചേർക്കുക',
      'editBatters': 'ബാറ്റർമാരെ മാറ്റുക',
      'addBowler': 'ബൗളറെ ചേർക്കുക',
      'editBowler': 'ബൗളറെ മാറ്റുക',
      'addPlayers': 'കളിക്കാരെ ചേർക്കുക',
      'editPlayers': 'കളിക്കാരെ മാറ്റുക',
      'teamName': 'ടീം പേര്',
      'players11': '11 കളിക്കാർ',
      'tapMic': 'സംസാരിക്കാൻ മൈക്ക് അമർത്തുക',
      'playerName': 'കളിക്കാരന്റെ പേര്',
      'scorecard': 'സ്കോർകാർഡ്',
      'wicket': 'വിക്കറ്റ്',
      'extra': 'എക്സ്ട്രാ',
      'undo': 'പഴയപടി',
      'changeBowler': 'ബൗളർ',
      'end': 'അവസാനിപ്പിക്കുക',
      'target': 'ലക്ഷ്യം',
      'need': 'ആവശ്യം',
      'rrr': 'ആവശ്യ റൺ റേറ്റ്',
      'last6': 'അവസാന 6 പന്തുകൾ',
      'inningsBreak': 'ഇന്നിങ്സ് ഇടവേള',
      'startChase': 'കളിക്കാരെ തിരഞ്ഞെടുത്ത് ചേസ് തുടങ്ങുക',
      'matchSummary': 'മത്സര സംഗ്രഹം',
      'currentPlayers': 'നിലവിലെ കളിക്കാർ',
      'deleteMatch': 'മത്സരം നീക്കണോ?',
      'delete': 'നീക്കുക',
      'noMatches': 'മത്സരങ്ങൾ ഇല്ല',
      'overComplete': 'ഓവർ പൂർത്തിയായി',
      'selectNewBowler': 'പുതിയ ബൗളറെ തിരഞ്ഞെടുക്കുക',
      'available': 'ലഭ്യം',
      'unavailable': 'ലഭ്യമല്ല',
      'selectExtra': 'എക്സ്ട്രാ തിരഞ്ഞെടുക്കുക',
      'howOut': 'ബാറ്റർ എങ്ങനെ ഔട്ട് ആയി?',
      'nextBatter': 'അടുത്ത ബാറ്റർ',
      'endMatch': 'മത്സരം അവസാനിപ്പിക്കുക',
      'topPerformers': 'മികച്ച 3 കളിക്കാർ',
      'ballsLeft': 'ശേഷിക്കുന്ന പന്തുകൾ',
      'selectStriker':
          'സ്ട്രൈക്കറെ തിരഞ്ഞെടുത്ത ശേഷം നോൺ-സ്ട്രൈക്കറെ തിരഞ്ഞെടുക്കുക',
      'selectNonStriker': 'നോൺ-സ്ട്രൈക്കറെ തിരഞ്ഞെടുക്കുക',
    },
    'kn': {
      'continue': 'ಮುಂದುವರಿಸಿ',
      'back': 'ಹಿಂದೆ',
      'cancel': 'ರದ್ದು',
      'save': 'ಉಳಿಸಿ',
      'confirm': 'ದೃಢೀಕರಿಸಿ',
      'teamASetup': 'ತಂಡ A ಸಿದ್ಧತೆ',
      'teamBSetup': 'ತಂಡ B ಸಿದ್ಧತೆ',
      'addTeamPlayers': 'ತಂಡ ಮತ್ತು ಆಟಗಾರರನ್ನು ಸೇರಿಸಿ',
      'battingFirst': 'ಮೊದಲು ಬ್ಯಾಟಿಂಗ್',
      'matchOvers': 'ಪಂದ್ಯದ ಓವರ್‌ಗಳು',
      'customOvers': 'ಕಸ್ಟಮ್ ಓವರ್‌ಗಳು',
      'openingPlayers': 'ಆರಂಭಿಕ ಆಟಗಾರರು',
      'chooseBattersBowler': 'ಬ್ಯಾಟರ್ ಮತ್ತು ಬೌಲರ್ ಆಯ್ಕೆ ಮಾಡಿ',
      'openingBatters': 'ಆರಂಭಿಕ ಬ್ಯಾಟರ್‌ಗಳು',
      'selectStrikerPartner': 'ಸ್ಟ್ರೈಕರ್ ಮತ್ತು ನಾನ್-ಸ್ಟ್ರೈಕರ್ ಆಯ್ಕೆ',
      'openingBowler': 'ಆರಂಭಿಕ ಬೌಲರ್',
      'selectCurrentBowler': 'ಪ್ರಸ್ತುತ ಬೌಲರ್ ಆಯ್ಕೆ',
      'addBatters': 'ಬ್ಯಾಟರ್‌ಗಳನ್ನು ಸೇರಿಸಿ',
      'editBatters': 'ಬ್ಯಾಟರ್‌ಗಳನ್ನು ಬದಲಿಸಿ',
      'addBowler': 'ಬೌಲರ್ ಸೇರಿಸಿ',
      'editBowler': 'ಬೌಲರ್ ಬದಲಿಸಿ',
      'addPlayers': 'ಆಟಗಾರರನ್ನು ಸೇರಿಸಿ',
      'editPlayers': 'ಆಟಗಾರರನ್ನು ಬದಲಿಸಿ',
      'teamName': 'ತಂಡದ ಹೆಸರು',
      'players11': '11 ಆಟಗಾರರು',
      'tapMic': 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
      'playerName': 'ಆಟಗಾರನ ಹೆಸರು',
      'scorecard': 'ಸ್ಕೋರ್‌ಕಾರ್ಡ್',
      'wicket': 'ವಿಕೆಟ್',
      'extra': 'ಎಕ್ಸ್ಟ್ರಾ',
      'undo': 'ಹಿಂದಕ್ಕೆ',
      'changeBowler': 'ಬೌಲರ್',
      'end': 'ಅಂತ್ಯ',
      'target': 'ಗುರಿ',
      'need': 'ಬೇಕಾಗಿದೆ',
      'rrr': 'ಅಗತ್ಯ ರನ್ ರೇಟ್',
      'last6': 'ಕೊನೆಯ 6 ಚೆಂಡುಗಳು',
      'inningsBreak': 'ಇನ್ನಿಂಗ್ಸ್ ವಿರಾಮ',
      'startChase': 'ಆಟಗಾರರನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಚೇಸ್ ಆರಂಭಿಸಿ',
      'matchSummary': 'ಪಂದ್ಯ ಸಾರಾಂಶ',
      'currentPlayers': 'ಪ್ರಸ್ತುತ ಆಟಗಾರರು',
      'deleteMatch': 'ಪಂದ್ಯ ಅಳಿಸಬೇಕೆ?',
      'delete': 'ಅಳಿಸಿ',
      'noMatches': 'ಪಂದ್ಯಗಳು ಇಲ್ಲ',
      'overComplete': 'ಓವರ್ ಪೂರ್ಣ',
      'selectNewBowler': 'ಹೊಸ ಬೌಲರ್ ಆಯ್ಕೆ ಮಾಡಿ',
      'available': 'ಲಭ್ಯ',
      'unavailable': 'ಲಭ್ಯವಿಲ್ಲ',
      'selectExtra': 'ಎಕ್ಸ್ಟ್ರಾ ಆಯ್ಕೆ',
      'howOut': 'ಬ್ಯಾಟರ್ ಹೇಗೆ ಔಟ್?',
      'nextBatter': 'ಮುಂದಿನ ಬ್ಯಾಟರ್',
      'endMatch': 'ಪಂದ್ಯ ಮುಗಿಸಿ',
      'topPerformers': 'ಅಗ್ರ 3 ಆಟಗಾರರು',
      'ballsLeft': 'ಉಳಿದ ಚೆಂಡುಗಳು',
      'selectStriker': 'ಸ್ಟ್ರೈಕರ್ ಆಯ್ಕೆ ಮಾಡಿ, ನಂತರ ನಾನ್-ಸ್ಟ್ರೈಕರ್ ಆಯ್ಕೆ ಮಾಡಿ',
      'selectNonStriker': 'ನಾನ್-ಸ್ಟ್ರೈಕರ್ ಆಯ್ಕೆ ಮಾಡಿ',
    },
    'pa': {
      'continue': 'ਜਾਰੀ ਰੱਖੋ',
      'back': 'ਵਾਪਸ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'save': 'ਸੇਵ ਕਰੋ',
      'confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'teamASetup': 'ਟੀਮ A ਸੈਟਅਪ',
      'teamBSetup': 'ਟੀਮ B ਸੈਟਅਪ',
      'addTeamPlayers': 'ਟੀਮ ਅਤੇ ਖਿਡਾਰੀ ਜੋੜੋ',
      'battingFirst': 'ਪਹਿਲਾਂ ਬੱਲੇਬਾਜ਼ੀ',
      'matchOvers': 'ਮੈਚ ਓਵਰ',
      'customOvers': 'ਕਸਟਮ ਓਵਰ',
      'openingPlayers': 'ਸ਼ੁਰੂਆਤੀ ਖਿਡਾਰੀ',
      'chooseBattersBowler': 'ਬੱਲੇਬਾਜ਼ ਅਤੇ ਗੇਂਦਬਾਜ਼ ਚੁਣੋ',
      'openingBatters': 'ਸ਼ੁਰੂਆਤੀ ਬੱਲੇਬਾਜ਼',
      'selectStrikerPartner': 'ਸਟ੍ਰਾਈਕਰ ਅਤੇ ਨਾਨ-ਸਟ੍ਰਾਈਕਰ ਚੁਣੋ',
      'openingBowler': 'ਸ਼ੁਰੂਆਤੀ ਗੇਂਦਬਾਜ਼',
      'selectCurrentBowler': 'ਮੌਜੂਦਾ ਗੇਂਦਬਾਜ਼ ਚੁਣੋ',
      'addBatters': 'ਬੱਲੇਬਾਜ਼ ਜੋੜੋ',
      'editBatters': 'ਬੱਲੇਬਾਜ਼ ਬਦਲੋ',
      'addBowler': 'ਗੇਂਦਬਾਜ਼ ਜੋੜੋ',
      'editBowler': 'ਗੇਂਦਬਾਜ਼ ਬਦਲੋ',
      'addPlayers': 'ਖਿਡਾਰੀ ਜੋੜੋ',
      'editPlayers': 'ਖਿਡਾਰੀ ਬਦਲੋ',
      'teamName': 'ਟੀਮ ਦਾ ਨਾਮ',
      'players11': '11 ਖਿਡਾਰੀ',
      'tapMic': 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
      'playerName': 'ਖਿਡਾਰੀ ਦਾ ਨਾਮ',
      'scorecard': 'ਸਕੋਰਕਾਰਡ',
      'wicket': 'ਵਿਕਟ',
      'extra': 'ਵਾਧੂ',
      'undo': 'ਵਾਪਸ ਲਓ',
      'changeBowler': 'ਗੇਂਦਬਾਜ਼',
      'end': 'ਖਤਮ',
      'target': 'ਟੀਚਾ',
      'need': 'ਲੋੜ',
      'rrr': 'ਲੋੜੀਂਦੀ ਰਨ ਰੇਟ',
      'last6': 'ਆਖਰੀ 6 ਗੇਂਦਾਂ',
      'inningsBreak': 'ਪਾਰੀ ਵਿਰਾਮ',
      'startChase': 'ਖਿਡਾਰੀ ਚੁਣੋ ਅਤੇ ਚੇਜ਼ ਸ਼ੁਰੂ ਕਰੋ',
      'matchSummary': 'ਮੈਚ ਸੰਖੇਪ',
      'currentPlayers': 'ਮੌਜੂਦਾ ਖਿਡਾਰੀ',
      'deleteMatch': 'ਮੈਚ ਮਿਟਾਉਣਾ?',
      'delete': 'ਮਿਟਾਓ',
      'noMatches': 'ਕੋਈ ਮੈਚ ਨਹੀਂ',
      'overComplete': 'ਓਵਰ ਪੂਰਾ',
      'selectNewBowler': 'ਨਵਾਂ ਗੇਂਦਬਾਜ਼ ਚੁਣੋ',
      'available': 'ਉਪਲਬਧ',
      'unavailable': 'ਉਪਲਬਧ ਨਹੀਂ',
      'selectExtra': 'ਵਾਧੂ ਚੁਣੋ',
      'howOut': 'ਬੱਲੇਬਾਜ਼ ਕਿਵੇਂ ਆਊਟ?',
      'nextBatter': 'ਅਗਲਾ ਬੱਲੇਬਾਜ਼',
      'endMatch': 'ਮੈਚ ਖਤਮ ਕਰੋ',
      'topPerformers': 'ਚੋਟੀ ਦੇ 3 ਖਿਡਾਰੀ',
      'ballsLeft': 'ਬਾਕੀ ਗੇਂਦਾਂ',
      'selectStriker': 'ਸਟ੍ਰਾਈਕਰ ਚੁਣੋ, ਫਿਰ ਨਾਨ-ਸਟ੍ਰਾਈਕਰ ਚੁਣੋ',
      'selectNonStriker': 'ਨਾਨ-ਸਟ੍ਰਾਈਕਰ ਚੁਣੋ',
    },
    'bn': {
      'continue': 'চালিয়ে যান',
      'back': 'ফিরে যান',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
      'confirm': 'নিশ্চিত করুন',
      'teamASetup': 'দল A সেটআপ',
      'teamBSetup': 'দল B সেটআপ',
      'addTeamPlayers': 'দল ও খেলোয়াড় যোগ করুন',
      'battingFirst': 'প্রথমে ব্যাটিং',
      'matchOvers': 'ম্যাচ ওভার',
      'customOvers': 'কাস্টম ওভার',
      'openingPlayers': 'শুরুর খেলোয়াড়',
      'chooseBattersBowler': 'ব্যাটার ও বোলার নির্বাচন করুন',
      'openingBatters': 'শুরুর ব্যাটার',
      'selectStrikerPartner': 'স্ট্রাইকার ও নন-স্ট্রাইকার নির্বাচন',
      'openingBowler': 'শুরুর বোলার',
      'selectCurrentBowler': 'বর্তমান বোলার নির্বাচন',
      'addBatters': 'ব্যাটার যোগ করুন',
      'editBatters': 'ব্যাটার পরিবর্তন',
      'addBowler': 'বোলার যোগ করুন',
      'editBowler': 'বোলার পরিবর্তন',
      'addPlayers': 'খেলোয়াড় যোগ করুন',
      'editPlayers': 'খেলোয়াড় পরিবর্তন',
      'teamName': 'দলের নাম',
      'players11': '১১ খেলোয়াড়',
      'tapMic': 'বলতে মাইক চাপুন',
      'playerName': 'খেলোয়াড়ের নাম',
      'scorecard': 'স্কোরকার্ড',
      'wicket': 'উইকেট',
      'extra': 'অতিরিক্ত',
      'undo': 'ফিরিয়ে নিন',
      'changeBowler': 'বোলার',
      'end': 'শেষ',
      'target': 'লক্ষ্য',
      'need': 'প্রয়োজন',
      'rrr': 'প্রয়োজনীয় রান রেট',
      'last6': 'শেষ ৬ বল',
      'inningsBreak': 'ইনিংস বিরতি',
      'startChase': 'খেলোয়াড় বেছে চেজ শুরু করুন',
      'matchSummary': 'ম্যাচ সারাংশ',
      'currentPlayers': 'বর্তমান খেলোয়াড়',
      'deleteMatch': 'ম্যাচ মুছবেন?',
      'delete': 'মুছুন',
      'noMatches': 'কোনো ম্যাচ নেই',
      'overComplete': 'ওভার শেষ',
      'selectNewBowler': 'নতুন বোলার নির্বাচন',
      'available': 'উপলব্ধ',
      'unavailable': 'অনুপলব্ধ',
      'selectExtra': 'অতিরিক্ত নির্বাচন',
      'howOut': 'ব্যাটার কীভাবে আউট?',
      'nextBatter': 'পরবর্তী ব্যাটার',
      'endMatch': 'ম্যাচ শেষ করুন',
      'topPerformers': 'সেরা ৩ খেলোয়াড়',
      'ballsLeft': 'বল বাকি',
      'selectStriker': 'স্ট্রাইকার বেছে তারপর নন-স্ট্রাইকার বেছে নিন',
      'selectNonStriker': 'নন-স্ট্রাইকার বেছে নিন',
    },
    'or': {
      'continue': 'ଜାରି ରଖନ୍ତୁ',
      'back': 'ପଛକୁ',
      'cancel': 'ବାତିଲ୍',
      'save': 'ସେଭ୍',
      'confirm': 'ନିଶ୍ଚିତ',
      'teamASetup': 'ଟିମ୍ A ସେଟଅପ୍',
      'teamBSetup': 'ଟିମ୍ B ସେଟଅପ୍',
      'addTeamPlayers': 'ଟିମ୍ ଓ ଖେଳାଳି ଯୋଡ଼ନ୍ତୁ',
      'battingFirst': 'ପ୍ରଥମେ ବ୍ୟାଟିଂ',
      'matchOvers': 'ମ୍ୟାଚ୍ ଓଭର',
      'customOvers': 'କଷ୍ଟମ୍ ଓଭର',
      'openingPlayers': 'ଆରମ୍ଭ ଖେଳାଳି',
      'chooseBattersBowler': 'ବ୍ୟାଟର ଓ ବୋଲର ବାଛନ୍ତୁ',
      'openingBatters': 'ଆରମ୍ଭ ବ୍ୟାଟର',
      'selectStrikerPartner': 'ଷ୍ଟ୍ରାଇକର ଓ ନନ୍-ଷ୍ଟ୍ରାଇକର ବାଛନ୍ତୁ',
      'openingBowler': 'ଆରମ୍ଭ ବୋଲର',
      'selectCurrentBowler': 'ବର୍ତ୍ତମାନ ବୋଲର ବାଛନ୍ତୁ',
      'addBatters': 'ବ୍ୟାଟର ଯୋଡ଼ନ୍ତୁ',
      'editBatters': 'ବ୍ୟାଟର ବଦଳାନ୍ତୁ',
      'addBowler': 'ବୋଲର ଯୋଡ଼ନ୍ତୁ',
      'editBowler': 'ବୋଲର ବଦଳାନ୍ତୁ',
      'addPlayers': 'ଖେଳାଳି ଯୋଡ଼ନ୍ତୁ',
      'editPlayers': 'ଖେଳାଳି ବଦଳାନ୍ତୁ',
      'teamName': 'ଟିମ୍ ନାମ',
      'players11': '୧୧ ଖେଳାଳି',
      'tapMic': 'କହିବାକୁ ମାଇକ୍ ଦବାନ୍ତୁ',
      'playerName': 'ଖେଳାଳି ନାମ',
      'scorecard': 'ସ୍କୋରକାର୍ଡ',
      'wicket': 'ୱିକେଟ୍',
      'extra': 'ଅତିରିକ୍ତ',
      'undo': 'ପଛକୁ ନିଅନ୍ତୁ',
      'changeBowler': 'ବୋଲର',
      'end': 'ଶେଷ',
      'target': 'ଲକ୍ଷ୍ୟ',
      'need': 'ଆବଶ୍ୟକ',
      'rrr': 'ଆବଶ୍ୟକ ରନ୍ ରେଟ୍',
      'last6': 'ଶେଷ ୬ ବଲ୍',
      'inningsBreak': 'ଇନିଂସ ବିରତି',
      'startChase': 'ଖେଳାଳି ବାଛି ଚେଜ୍ ଆରମ୍ଭ',
      'matchSummary': 'ମ୍ୟାଚ୍ ସାରାଂଶ',
      'currentPlayers': 'ବର୍ତ୍ତମାନ ଖେଳାଳି',
      'deleteMatch': 'ମ୍ୟାଚ୍ ଡିଲିଟ୍?',
      'delete': 'ଡିଲିଟ୍',
      'noMatches': 'କୌଣସି ମ୍ୟାଚ୍ ନାହିଁ',
      'overComplete': 'ଓଭର ସମ୍ପୂର୍ଣ୍ଣ',
      'selectNewBowler': 'ନୂଆ ବୋଲର ବାଛନ୍ତୁ',
      'available': 'ଉପଲବ୍ଧ',
      'unavailable': 'ଉପଲବ୍ଧ ନୁହେଁ',
      'selectExtra': 'ଅତିରିକ୍ତ ବାଛନ୍ତୁ',
      'howOut': 'ବ୍ୟାଟର କିପରି ଆଉଟ୍?',
      'nextBatter': 'ପରବର୍ତ୍ତୀ ବ୍ୟାଟର',
      'endMatch': 'ମ୍ୟାଚ୍ ଶେଷ କରନ୍ତୁ',
      'topPerformers': 'ଶ୍ରେଷ୍ଠ ୩ ଖେଳାଳି',
      'ballsLeft': 'ବଲ୍ ବାକି',
      'selectStriker': 'ଷ୍ଟ୍ରାଇକର ବାଛନ୍ତୁ, ତାପରେ ନନ୍-ଷ୍ଟ୍ରାଇକର ବାଛନ୍ତୁ',
      'selectNonStriker': 'ନନ୍-ଷ୍ଟ୍ରାଇକର ବାଛନ୍ତୁ',
    },
    'as': {
      'continue': 'অব্যাহত ৰাখক',
      'back': 'পিছলৈ',
      'cancel': 'বাতিল',
      'save': 'সংৰক্ষণ',
      'confirm': 'নিশ্চিত কৰক',
      'teamASetup': 'দল A ছেটআপ',
      'teamBSetup': 'দল B ছেটআপ',
      'addTeamPlayers': 'দল আৰু খেলুৱৈ যোগ কৰক',
      'battingFirst': 'প্ৰথমে বেটিং',
      'matchOvers': 'মেচ অভাৰ',
      'customOvers': 'কাষ্টম অভাৰ',
      'openingPlayers': 'আৰম্ভণিৰ খেলুৱৈ',
      'chooseBattersBowler': 'বেটাৰ আৰু বলাৰ বাছক',
      'openingBatters': 'আৰম্ভণিৰ বেটাৰ',
      'selectStrikerPartner': 'ষ্ট্ৰাইকাৰ আৰু নন-ষ্ট্ৰাইকাৰ বাছক',
      'openingBowler': 'আৰম্ভণিৰ বলাৰ',
      'selectCurrentBowler': 'বৰ্তমান বলাৰ বাছক',
      'addBatters': 'বেটাৰ যোগ কৰক',
      'editBatters': 'বেটাৰ সলনি কৰক',
      'addBowler': 'বলাৰ যোগ কৰক',
      'editBowler': 'বলাৰ সলনি কৰক',
      'addPlayers': 'খেলুৱৈ যোগ কৰক',
      'editPlayers': 'খেলুৱৈ সলনি কৰক',
      'teamName': 'দলৰ নাম',
      'players11': '১১ খেলুৱৈ',
      'tapMic': 'ক’বলৈ মাইক টিপক',
      'playerName': 'খেলুৱৈৰ নাম',
      'scorecard': 'স্ক’ৰকাৰ্ড',
      'wicket': 'উইকেট',
      'extra': 'অতিৰিক্ত',
      'undo': 'পিছলৈ লওক',
      'changeBowler': 'বলাৰ',
      'end': 'শেষ',
      'target': 'লক্ষ্য',
      'need': 'প্ৰয়োজন',
      'rrr': 'প্ৰয়োজনীয় ৰান ৰেট',
      'last6': 'শেষ ৬ বল',
      'inningsBreak': 'ইনিংছ বিৰতি',
      'startChase': 'খেলুৱৈ বাছি চেজ আৰম্ভ কৰক',
      'matchSummary': 'মেচ সাৰাংশ',
      'currentPlayers': 'বৰ্তমান খেলুৱৈ',
      'deleteMatch': 'মেচ মচিবনে?',
      'delete': 'মচক',
      'noMatches': 'কোনো মেচ নাই',
      'overComplete': 'অভাৰ সম্পূৰ্ণ',
      'selectNewBowler': 'নতুন বলাৰ বাছক',
      'available': 'উপলব্ধ',
      'unavailable': 'উপলব্ধ নহয়',
      'selectExtra': 'অতিৰিক্ত বাছক',
      'howOut': 'বেটাৰ কেনেকৈ আউট?',
      'nextBatter': 'পৰৱৰ্তী বেটাৰ',
      'endMatch': 'মেচ শেষ কৰক',
      'topPerformers': 'শীৰ্ষ ৩ খেলুৱৈ',
      'ballsLeft': 'বল বাকী',
      'selectStriker': 'ষ্ট্ৰাইকাৰ বাছক, তাৰ পিছত নন-ষ্ট্ৰাইকাৰ বাছক',
      'selectNonStriker': 'নন-ষ্ট্ৰাইকাৰ বাছক',
    },
    'gu': {
      'continue': 'આગળ વધો',
      'back': 'પાછા',
      'cancel': 'રદ કરો',
      'save': 'સાચવો',
      'confirm': 'પુષ્ટિ કરો',
      'teamASetup': 'ટીમ A સેટઅપ',
      'teamBSetup': 'ટીમ B સેટઅપ',
      'addTeamPlayers': 'ટીમ અને ખેલાડીઓ ઉમેરો',
      'battingFirst': 'પહેલા બેટિંગ',
      'matchOvers': 'મેચ ઓવર',
      'customOvers': 'કસ્ટમ ઓવર',
      'openingPlayers': 'શરૂઆતના ખેલાડીઓ',
      'chooseBattersBowler': 'બેટર અને બોલર પસંદ કરો',
      'openingBatters': 'ઓપનિંગ બેટર્સ',
      'selectStrikerPartner': 'સ્ટ્રાઇકર અને નોન-સ્ટ્રાઇકર પસંદ કરો',
      'openingBowler': 'ઓપનિંગ બોલર',
      'selectCurrentBowler': 'હાલનો બોલર પસંદ કરો',
      'addBatters': 'બેટર્સ ઉમેરો',
      'editBatters': 'બેટર્સ બદલો',
      'addBowler': 'બોલર ઉમેરો',
      'editBowler': 'બોલર બદલો',
      'addPlayers': 'ખેલાડીઓ ઉમેરો',
      'editPlayers': 'ખેલાડીઓ બદલો',
      'teamName': 'ટીમનું નામ',
      'players11': '11 ખેલાડીઓ',
      'tapMic': 'બોલવા માટે માઇક દબાવો',
      'playerName': 'ખેલાડીનું નામ',
      'scorecard': 'સ્કોરકાર્ડ',
      'wicket': 'વિકેટ',
      'extra': 'એક્સ્ટ્રા',
      'undo': 'પાછું લો',
      'changeBowler': 'બોલર',
      'end': 'સમાપ્ત',
      'target': 'લક્ષ્ય',
      'need': 'જરૂર',
      'rrr': 'જરૂરી રન રેટ',
      'last6': 'છેલ્લા 6 બોલ',
      'inningsBreak': 'ઇનિંગ્સ વિરામ',
      'startChase': 'ખેલાડીઓ પસંદ કરી ચેઝ શરૂ કરો',
      'matchSummary': 'મેચ સારાંશ',
      'currentPlayers': 'હાલના ખેલાડીઓ',
      'deleteMatch': 'મેચ કાઢી નાખવો?',
      'delete': 'કાઢી નાખો',
      'noMatches': 'કોઈ મેચ મળી નથી',
      'overComplete': 'ઓવર પૂર્ણ',
      'selectNewBowler': 'નવો બોલર પસંદ કરો',
      'available': 'ઉપલબ્ધ',
      'unavailable': 'ઉપલબ્ધ નથી',
      'selectExtra': 'એક્સ્ટ્રા પસંદ કરો',
      'howOut': 'બેટર કેવી રીતે આઉટ થયો?',
      'nextBatter': 'આગલો બેટર',
      'endMatch': 'મેચ સમાપ્ત કરો',
      'topPerformers': 'શ્રેષ્ઠ 3 ખેલાડીઓ',
      'ballsLeft': 'બાકી બોલ',
      'selectStriker': 'સ્ટ્રાઇકર પસંદ કરો, પછી નોન-સ્ટ્રાઇકર પસંદ કરો',
      'selectNonStriker': 'નોન-સ્ટ્રાઇકર પસંદ કરો',
    },
  };

  String text(String key) =>
      _common[locale.languageCode]?[key] ??
      _values[locale.languageCode]?[key] ??
      _common['en']?[key] ??
      _values['en']![key] ??
      key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (value) => value.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).text(key);
}
